footprint: [[-0.31, -0.23], [-0.31, 0.23], [0.56, 0.23], [0.56, -0.23]]
# footprint: [[-0.18, -0.17], [-0.18, 0.17], [0.45, 0.17], [0.45, -0.17]]

robot_base_frame: base_link
update_frequency: 3.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.0
raytrace_range: 5.5

plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: obstacles, type: "costmap_2d::VoxelLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles:
    observation_sources: laser
    laser: {sensor_frame: camera_link, data_type: LaserScan, topic: scan, clearing: true, marking: true, inf_is_valid: true}

inflation:
    inflation_radius: 0.6
    cost_scaling_factor: 10.0